// <auto-generated />
namespace Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class newTavles2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newTavles2));
        
        string IMigrationMetadata.Id
        {
            get { return "201909240028178_newTavles2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
